k: 10
encoder_type: "FC"
input_size: 784
hidden_size: 512 #512
latent_dim: 10
recon_loss_type: "BCE"
eps: 0
model_name: "GMVAE"
loss_name: "Loss"
encoder_kwargs: {dropout: 0.0}
decoder_kwargs: {return_probs: True}